// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    courseURL: "http://127.0.0.1:83/webservice/rest/server.php",
    courseId: "15"
  }
});

export default function() {
  postman[Request]({
    name: "CREATE COURSE",
    id: "7f8b2e24-cfde-41fa-8ebb-195ded853eb1",
    method: "POST",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_create_courses&courses[0][fullname]=mycourses&courses[0][shortname]=mycourses123&courses[0][categoryid]=1&courses[0][visible]=1&courses[0][summary]=text&courses[0][enablecompletion]=0&courses[0][summaryformat]=1&courses[0][format]=topics&courses[0][numsections]=0",
    data: {},
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var response = JSON.parse(responseBody);
        console.log(response[0].id);
        postman.setEnvironmentVariable("courseId", response[0].id);
      });
    }
  });

  postman[Request]({
    name: "GET COURSE",
    id: "163e04aa-a8fe-45dc-897b-930462727330",
    method: "GET",
    address:
      "http://127.0.0.1:83/webservice/rest/server.php?wstoken=585a5e34abe199537fec2640b8252ef7&wsfunction=core_course_get_courses&options[ids][0]=11&moodlewsrestformat=json",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var legalOrganizationId = JSON.parse(responseBody);
        console.log(legalOrganizationId[0].id);
      });
    }
  });

  postman[Request]({
    name: "DELETE COURSE",
    id: "21b39f7a-1dee-40a6-82cb-f37efc9f845e",
    method: "DELETE",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_delete_courses&courseids[0]={{courseId}}"
  });
}
