// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "CREATE COURSE",
    id: "a40d8ec5-44ed-4a45-9f52-bedcd70db85a",
    method: "POST",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_create_courses&courses[0][fullname]=mycourses&courses[0][shortname]=mycourses123&courses[0][categoryid]=1&courses[0][visible]=1&courses[0][summary]=text&courses[0][enablecompletion]=0&courses[0][summaryformat]=1&courses[0][format]=topics&courses[0][numsections]=0",
    data: {},
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var response = JSON.parse(responseBody);
        console.log(response[0].id);
        postman.setEnvironmentVariable("courseId", response[0].id);
      });
    }
  });

  postman[Request]({
    name: "GET COURSE",
    id: "0c232f43-1fb8-4ae5-aa0d-027b6f6b4141",
    method: "GET",
    address:
      "http://127.0.0.1:83/webservice/rest/server.php?wstoken=585a5e34abe199537fec2640b8252ef7&wsfunction=core_course_get_courses&options[ids][0]=11&moodlewsrestformat=json",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
        var legalOrganizationId = JSON.parse(responseBody);
        console.log(legalOrganizationId[0].id);
      });
    }
  });

  postman[Request]({
    name: "DELETE COURSE",
    id: "e9097c81-3b75-415f-b990-5377db17c533",
    method: "DELETE",
    address:
      "{{courseURL}}?wstoken=585a5e34abe199537fec2640b8252ef7&moodlewsrestformat=json&wsfunction=core_course_delete_courses&courseids[0]={{courseId}}"
  });
}
